version: "3.11"
services:
  tgbot:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: zodiac_prediction
    command: poetry run python main.py
    depends_on:
      - db
  db:
     image: postgres
     restart: always
     container_name: db
     volumes:
         - postgres:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASS}
       - POSTGRES_PORT=${DB_PORT}
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_HOST=${DB_HOST}
     env_file:
       - .env
     ports:
       - "5432:5432"

volumes:
  postgres:
