version: "3.11"
services:
  tgbot:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: zodiac_prediction
    command: python main.py
    depends_on:
      - db
      - redis
    networks:
      - celery_net

  db:
     image: postgres
     restart: always
     container_name: db
     volumes:
         - postgres:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASS}
       - POSTGRES_PORT=${DB_PORT}
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_HOST=${DB_HOST}
     env_file:
       - .env
     ports:
       - "5432:5432"
     networks:
       - celery_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass ${BROKER_PASSWORD}
    environment:
      - BROKER_URL=${BROKER_URL}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
    env_file:
      - .env
    networks:
      - celery_net

  celery:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: celery_worker
    command: bash -c "celery -A celery_app:app worker --beat -l info"
    depends_on:
      - tgbot
      - db
      - redis
    environment:
      - CELERY_CONFIG_MODULE=celeryconfig
    networks:
      - celery_net

volumes:
  postgres:

networks:
  celery_net:
    driver: bridge