"""add new tables

Revision ID: 098830a768a7
Revises: c049d64163d9
Create Date: 2023-07-27 09:31:56.633173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098830a768a7'
down_revision = 'c049d64163d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_horoscope_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('zodiac_sign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zodiac_sign_id'], ['zodiac_signs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('love_horoscope_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('zodiac_sign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zodiac_sign_id'], ['zodiac_signs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('love_horoscope_data')
    op.drop_table('finance_horoscope_data')
    op.drop_table('users')
    # ### end Alembic commands ###
